### ISSUE TITLE
feature/input-from-keep

### ISSUE THREAD

**Issue by lbowes** [lbowes/keep-to-calendar#1]
## Summary
As a *user*, I want *to be able to configure the application with information from Google Keep*, so I can *interface with it easily*.

## Tasks
- [ ] Initialise the (unofficial) Google Keep API (load creds from separate file)
- [ ] Use it to fetch a complete list of card titles
- [ ] Output these titles to a json array in a file called `config.json` (created if it doesn't exist)

## Acceptance criteria
After running `keep_to_calendar.py`, a local `.json` file should be populated with an array of card titles from Google Keep.
