### ISSUE TITLE
test/activity-loading-integration-tests

### ISSUE THREAD

**Issue by lbowes** [lbowes/keep-to-calendar#16]
### Description
Now that activity descriptions are loaded from disk, we can provide test cases in separate files. Load the files and check that the output of the activity generation is correct. This will make testing activity inheritance easier.

### TODO
- [x] Create a 'test_data' directory in the root of the project
- [x] Add 3 different activity description json files to this directory, that each contain different sets of activity descriptions
- [x] Rename current `test_activity_loading.py` file to `test_units.py` and add a `test_integration.py` file, that contains tests for the complete loading pipeline using the new files above
