### ISSUE TITLE
docs/readme

### ISSUE THREAD

**Issue by lbowes** [lbowes/keep-to-calendar#17]
### Description
The project should have a suitable README for the project

### TODO
Add the following sections:
- [x] Aim/problem statement/background/intro
- [ ] How to run
- [ ] Process diagram?
- [ ] Screenshots of input, processing, output stages
- [ ] Third party libraries
