### ISSUE TITLE
feature/output-to-calendar

### ISSUE THREAD

**Issue by lbowes** [lbowes/keep-to-calendar#2]
## Summary
As a *user*, I want *to automatically add/remove events on my Google Calendar*, so I can *use generated blocks of time to plan a schedule*.

## Tasks
- [ ] Initialise the Google Calendar API (load creds from separate file)
- [ ] Use it to add two events both one hour after the time that the script is run, lasting 30 mins, titled "Event A" and "Event B" respectively
- [ ] Events above should contain descriptions that match their titles
- [ ] Use the API to remove "Event A"

## Acceptance criteria
After running `keep_to_calendar.py`, the linked Google Calendar should only contain "Event B" scheduled for one hour ahead, lasting 30 mins.
