### ISSUE TITLE
feature/time-block-event-gen

### ISSUE THREAD

**Issue by lbowes** [lbowes/keep-to-calendar#34]
### Description
New calendar events should be generated in time blocks. Blocks should then be combined and converted into events using RLE.

### TODO
- [x] Add a function for converting a `timedelta` object into a number of time blocks, given the length of one block in minutes.
- [x] Create a string in which each character represents a block of time in the input time range.
- [x] Map each activity in the set generated from descriptions to a character (`dict`)
- [x] To test the system works, set a different activity at each block (looping round the end of the list)
- [ ] Convert this output string into a set of event tuples (name, start datetime, end datetime)

**Comment by lbowes** [comment]
Instead of a string, block generation output is now a list of `int`s (where each `int` represents an index into the `activity` array, or free time if -1).
