### ISSUE TITLE
feature/yaml-file-support

### ISSUE THREAD

**Issue by lbowes** [lbowes/keep-to-calendar#42]
### Description
The user should be able to supply an activity description file in the YAML file format.

### TODO
- [ ] `pip install pyyaml` (add this to `requirements.txt`)
- [ ] If not specified, the default activity file should be detected in the same directory as the script, by name e.g. `activity_descriptions`, `activity_descs` or `descs`.
- [ ] The activity loading from file needs to be slightly modified to work with whichever file type it is given.
