### ISSUE TITLE
Separate event plotter into new repo

### ISSUE THREAD

**Issue by lbowes** [lbowes/keep-to-calendar#52]
### Description
The `plot_events.py` file should be used as the basis of a new repository.

### TODO
- [ ] Decouple `plot_events.py` from `keep_to_calendar` completely, including tests
- [ ] Create new repo
- [ ] Add functionality as pip package
